<a href="https://colab.research.google.com/github/rogertbarrow/DataCleaning/blob/main/CarOwnersNationwide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install googletrans==4.0.0-rc1

Requirement already satisfied: googletrans==4.0.0-rc1 in /usr/local/lib/python3.10/dist-packages (4.0.0rc1)
Requirement already satisfied: httpx==0.13.3 in /usr/local/lib/python3.10/dist-packages (from googletrans==4.0.0-rc1) (0.13.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2024.8.30)
Requirement already satisfied: hstspreload in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2024.10.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.4)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.5.0)
Requirement already satisfied: httpcore==0.9.* in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.1)
Requirement already satisfied: h11<0.10,>=0.8 in /usr/local/lib/python3.10/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.0)
Requirement already satisfied: h2==3.* in /usr/local/lib/python3.10/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.10/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.10/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.0)

In [2]:
import pandas as pd
import re
from googletrans import Translator

In [3]:
# Load the dataset from the CSV file
df = pd.read_csv('760k-Car-Owners-Nationwide-China-csv-2020.csv', low_memory=False)

In [4]:
# Display the first few rows of the dataset to understand its content
print("The first few rows of the dataset:")
print(df.head())

The first few rows of the dataset:
                 车架号   姓名                 身份证 性别           手机  \
0  LSGLP84X2DF248935  马宏刚  432326197709250132  男  13873752623
1  LSGSA52M7ED215740   杨威  42060619860917201X  男  15605965992
2  LSGPB54U4ED067501   袁凯  342901199203026435  男  18301866904
3  LSGPC54U4EF169771  陈博天  420625198711290070  男  18838133331
4  LSGGF53W3EH096133   徐彬  110106197711301514  男  13801274963

                    邮箱    省   城市                    地址        邮编  ...  \
0     534260098@qq.com  湖南省  益阳市       湖南省安化县东坪镇杨溪路31号  413000.0  ...
1  15605965992@163.com  湖北省  武汉市         武汉市洪山区鲁磨路485号  430000.0  ...
2  tongtu96818@126.com  上海市  上海市        上海市闵行区中春路1500号  201109.0  ...
3  18838133331@139.com  河南省  郑州市  河南省郑州市商鼎路107附道向东200米  450000.0  ...
4  13801274963@126.com  北京市  北京市      北京市丰台区卢沟桥五里店336号  100070.0  ...

             月薪  婚姻  教育 BRAND       车系                 车型  \
0      50000元以上  已婚  大专   雪佛兰  科帕奇 CKD  科帕奇 C140  CKD 2.4
1    6000－9999元  已婚  大专   雪佛兰    新赛欧三厢           新赛欧三厢豪华型
2    6000－9999元  未婚  大专    别克    英朗 GT           英朗 GT GL
3    3000－5999元  未婚  大专   雪佛兰    科鲁兹三厢           科鲁兹三厢 SE
4  20000－24999元  已婚  大本    别克     全新君越            全新君越 GL

                                         配置                              颜色  \
0  Captiva 2.4 LT AWD(Comfort)(5seat) 13含附件                     晶石黑;耀石黑;旷夜黑
1                       新赛欧三厢1.4MT幸福III版 14  珍珠白;幻白;象牙白;茉莉白;雪域白;闪电白;流光白;皓沙白
2                        英朗 GT 1.6L手动进取型 14                             卡其金
3                        科鲁兹三厢 1.6 SE MT 14  珍珠白;幻白;象牙白;茉莉白;雪域白;闪电白;流光白;皓沙白
4           全新君越 2.4L SIDI 精英舒适型(加热)(棕红) 14               墨玉黑;元黑;炫黑;钢琴黑;爵士黑

             发动机号 Unnamed: 21
0  LE9*140800786*
1  LCU*D83120897*
2  LDE*140021440*
3  LDE*141090863*
4  LAF*140370116*

[5 rows x 22 columns]

In [5]:
# Get basic information about the dataset
print("\nBasic information about the dataset:")
print(df.info())

Basic information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 763386 entries, 0 to 763385
Data columns (total 22 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   车架号          763386 non-null  object
 1   姓名           763386 non-null  object
 2   身份证          763319 non-null  object
 3   性别           761784 non-null  object
 4   手机           763386 non-null  object
 5   邮箱           761784 non-null  object
 6   省            762492 non-null  object
 7   城市           762491 non-null  object
 8   地址           763385 non-null  object
 9   邮编           763385 non-null  float64
 10  生日           763385 non-null  object
 11  行业           761783 non-null  object
 12  月薪           761783 non-null  object
 13  婚姻           761783 non-null  object
 14  教育           761783 non-null  object
 15  BRAND        762491 non-null  object
 16  车系           763385 non-null  object
 17  车型           763385 non-null  object
 18  配置           762491 non-null  object
 19  颜色           762491 non-null  object
 20  发动机号         737316 non-null  object
 21  Unnamed: 21  763385 non-null  object
dtypes: float64(1), object(21)
memory usage: 128.1+ MB
None

In [6]:
# prompt: How do I translate the column headings using a translation library?

# Initialize the translator
translator = Translator()

# Translate the column headings
new_column_names = []
for col in df.columns:
  try:
    translated_col = translator.translate(col, dest='en').text
    new_column_names.append(translated_col)
  except:
    new_column_names.append(col)  # Keep original if translation fails


# Assign the new column names to the dataframe
df.columns = new_column_names

# Display the first few rows of the dataset with translated column headings
print("The first few rows of the dataset with translated column headings:")
print(df.head())
# Get basic information about the dataset
print("\nBasic information about the dataset:")
print(df.info())

The first few rows of the dataset with translated column headings:
        Frame number Name             ID card gender   cell phone  \
0  LSGLP84X2DF248935  马宏刚  432326197709250132      男  13873752623
1  LSGSA52M7ED215740   杨威  42060619860917201X      男  15605965992
2  LSGPB54U4ED067501   袁凯  342901199203026435      男  18301866904
3  LSGPC54U4EF169771  陈博天  420625198711290070      男  18838133331
4  LSGGF53W3EH096133   徐彬  110106197711301514      男  13801274963

                  Mail Province City               address  post code  ...  \
0     534260098@qq.com      湖南省  益阳市       湖南省安化县东坪镇杨溪路31号   413000.0  ...
1  15605965992@163.com      湖北省  武汉市         武汉市洪山区鲁磨路485号   430000.0  ...
2  tongtu96818@126.com      上海市  上海市        上海市闵行区中春路1500号   201109.0  ...
3  18838133331@139.com      河南省  郑州市  河南省郑州市商鼎路107附道向东200米   450000.0  ...
4  13801274963@126.com      北京市  北京市      北京市丰台区卢沟桥五里店336号   100070.0  ...

  Monthly salary marriage educate BRAND      Car              Model  \
0       50000元以上       已婚      大专   雪佛兰  科帕奇 CKD  科帕奇 C140  CKD 2.4
1     6000－9999元       已婚      大专   雪佛兰    新赛欧三厢           新赛欧三厢豪华型
2     6000－9999元       未婚      大专    别克    英朗 GT           英朗 GT GL
3     3000－5999元       未婚      大专   雪佛兰    科鲁兹三厢           科鲁兹三厢 SE
4   20000－24999元       已婚      大本    别克     全新君越            全新君越 GL

                              Configuration                           color  \
0  Captiva 2.4 LT AWD(Comfort)(5seat) 13含附件                     晶石黑;耀石黑;旷夜黑
1                       新赛欧三厢1.4MT幸福III版 14  珍珠白;幻白;象牙白;茉莉白;雪域白;闪电白;流光白;皓沙白
2                        英朗 GT 1.6L手动进取型 14                             卡其金
3                        科鲁兹三厢 1.6 SE MT 14  珍珠白;幻白;象牙白;茉莉白;雪域白;闪电白;流光白;皓沙白
4           全新君越 2.4L SIDI 精英舒适型(加热)(棕红) 14               墨玉黑;元黑;炫黑;钢琴黑;爵士黑

     Motor number Unnamed: 21
0  LE9*140800786*
1  LCU*D83120897*
2  LDE*140021440*
3  LDE*141090863*
4  LAF*140370116*

[5 rows x 22 columns]

Basic information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 763386 entries, 0 to 763385
Data columns (total 22 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Frame number    763386 non-null  object
 1   Name            763386 non-null  object
 2   ID card         763319 non-null  object
 3   gender          761784 non-null  object
 4   cell phone      763386 non-null  object
 5   Mail            761784 non-null  object
 6   Province        762492 non-null  object
 7   City            762491 non-null  object
 8   address         763385 non-null  object
 9   post code       763385 non-null  float64
 10  Birthday        763385 non-null  object
 11  industry        761783 non-null  object
 12  Monthly salary  761783 non-null  object
 13  marriage        761783 non-null  object
 14  educate         761783 non-null  object
 15  BRAND           762491 non-null  object
 16  Car             763385 non-null  object
 17  Model           763385 non-null  object
 18  Configuration   762491 non-null  object
 19  color           762491 non-null  object
 20  Motor number    737316 non-null  object
 21  Unnamed: 21     763385 non-null  object
dtypes: float64(1), object(21)
memory usage: 128.1+ MB
None

In [7]:
# prompt: How do I drop one or more columns from the dataframe?

# Assuming you want to drop columns 'Monthly salary', 'educate', etc.
df = df.drop(['Frame number', 'Monthly salary', 'educate', 'BRAND', 'Car', 'Model', 'Configuration', 'color', 'Motor number', 'Unnamed: 21'], axis=1)

# Display the updated dataframe
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 763386 entries, 0 to 763385
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Name        763386 non-null  object
 1   ID card     763319 non-null  object
 2   gender      761784 non-null  object
 3   cell phone  763386 non-null  object
 4   Mail        761784 non-null  object
 5   Province    762492 non-null  object
 6   City        762491 non-null  object
 7   address     763385 non-null  object
 8   post code   763385 non-null  float64
 9   Birthday    763385 non-null  object
 10  industry    761783 non-null  object
 11  marriage    761783 non-null  object
dtypes: float64(1), object(11)
memory usage: 69.9+ MB
None

In [8]:
# Check for missing values
print(df.isnull().sum())

Name             0
ID card         67
gender        1602
cell phone       0
Mail          1602
Province       894
City           895
address          1
post code        1
Birthday         1
industry      1603
marriage      1603
dtype: int64

In [9]:
# Fill in the missing post code values.
df['post code'] = df['post code'].fillna(0.0)

In [10]:
df.head()

,Name,ID card,gender,cell phone,Mail,Province,City,address,post code,Birthday,industry,marriage
0,马宏刚,432326197709250132,男,13873752623,534260098@qq.com,湖南省,益阳市,湖南省安化县东坪镇杨溪路31号,413000.0,1977-09-25,其他,已婚
1,杨威,42060619860917201X,男,15605965992,15605965992@163.com,湖北省,武汉市,武汉市洪山区鲁磨路485号,430000.0,1986-09-17,其他,已婚
2,袁凯,342901199203026435,男,18301866904,tongtu96818@126.com,上海市,上海市,上海市闵行区中春路1500号,201109.0,1992-03-02,其他,未婚
3,陈博天,420625198711290070,男,18838133331,18838133331@139.com,河南省,郑州市,河南省郑州市商鼎路107附道向东200米,450000.0,1987-11-29,房地产/建筑业,未婚
4,徐彬,110106197711301514,男,13801274963,13801274963@126.com,北京市,北京市,北京市丰台区卢沟桥五里店336号,100070.0,1977-11-30,日用品、耐用品、工业用品制造业,已婚

In [11]:
# Convert 'post code' values from floating point to integer numbers and then to
# strings.
df['post code'] = df['post code'].astype(int).astype(str)

In [12]:
df.head()

,Name,ID card,gender,cell phone,Mail,Province,City,address,post code,Birthday,industry,marriage
0,马宏刚,432326197709250132,男,13873752623,534260098@qq.com,湖南省,益阳市,湖南省安化县东坪镇杨溪路31号,413000,1977-09-25,其他,已婚
1,杨威,42060619860917201X,男,15605965992,15605965992@163.com,湖北省,武汉市,武汉市洪山区鲁磨路485号,430000,1986-09-17,其他,已婚
2,袁凯,342901199203026435,男,18301866904,tongtu96818@126.com,上海市,上海市,上海市闵行区中春路1500号,201109,1992-03-02,其他,未婚
3,陈博天,420625198711290070,男,18838133331,18838133331@139.com,河南省,郑州市,河南省郑州市商鼎路107附道向东200米,450000,1987-11-29,房地产/建筑业,未婚
4,徐彬,110106197711301514,男,13801274963,13801274963@126.com,北京市,北京市,北京市丰台区卢沟桥五里店336号,100070,1977-11-30,日用品、耐用品、工业用品制造业,已婚

In [13]:
# prompt: Please fill all missing values with the string 'NA'.

# Fill missing values with 'NA'
df.fillna('NA', inplace=True)

In [14]:
# Re-check for missing values
print(df.isnull().sum())

Name          0
ID card       0
gender        0
cell phone    0
Mail          0
Province      0
City          0
address       0
post code     0
Birthday      0
industry      0
marriage      0
dtype: int64

In [15]:
# Identify duplicates (excluding the first occurrence)
duplicates = df[df.duplicated(subset=['ID card'], keep='first')]

# Export duplicate rows to a separate CSV file
duplicates.to_csv('duplicate_id_cards.csv', index=False)

# Drop duplicates from the original DataFrame, keeping the first occurrence
df_unique = df.drop_duplicates(subset=['ID card'], keep='first')

In [16]:
df_unique.info()

<class 'pandas.core.frame.DataFrame'>
Index: 746310 entries, 0 to 763385
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Name        746310 non-null  object
 1   ID card     746310 non-null  object
 2   gender      746310 non-null  object
 3   cell phone  746310 non-null  object
 4   Mail        746310 non-null  object
 5   Province    746310 non-null  object
 6   City        746310 non-null  object
 7   address     746310 non-null  object
 8   post code   746310 non-null  object
 9   Birthday    746310 non-null  object
 10  industry    746310 non-null  object
 11  marriage    746310 non-null  object
dtypes: object(12)
memory usage: 74.0+ MB

In [17]:
# prompt: Please check for invalid e-mail addresses, remove those rows, and export them to a separate .csv file.

# Define a regular expression pattern for valid email addresses
email_pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"

# Find rows with invalid email addresses
invalid_emails_df = df_unique[~df_unique['Mail'].str.match(email_pattern, na=False)]

# Remove rows with invalid email addresses from the original DataFrame
df_valid_emails = df_unique[df_unique['Mail'].str.match(email_pattern, na=False)]

# Export the rows with invalid emails to a separate CSV file
invalid_emails_df.to_csv('rows_with_invalid_emails.csv', index=False)

In [18]:
# Reset the index
df_indexed = df_valid_emails.reset_index(drop=True)

In [19]:
df_indexed.tail()

,Name,ID card,gender,cell phone,Mail,Province,City,address,post code,Birthday,industry,marriage
744486,李西彩,371327198702032726,女,15264937348,yuantong_junan1@126.com,山东省,临沂市,山东省临沂市莒南县岭泉镇前左山村36号,276600,1987-02-03,其他,已婚
744487,王汉军,320821197112091333,男,13505248709,342863163@qq.com,江苏省,淮安市,江苏省淮安市淮阴区南陈集镇头堡村头堡庄3号,223000,1971-12-09,广告/媒体/出版/演艺体育业,已婚
744488,何信成,33050119890322933X,男,13735108339,13735108339@163.COM,浙江省,湖州市,浙江省湖州市吴兴区埭溪镇老虎潭安置区22幢403室,313000,1989-03-22,日用品、耐用品、工业用品制造业,未婚
744489,周雪,210421198605120240,男,13384665949,13384665949@139.com,黑龙江省,哈尔滨市,哈尔滨市香坊区旭东街35-4号翠海花园12栋1单元702室,150000,1986-05-12,日用品、耐用品、工业用品制造业,已婚
744490,黄武东,500383199012202117,男,13541338187,13541338187@139.com,四川省,成都市,龙泉驿区西河镇美辰东方7栋1单元702号,610100,1990-12-20,教育/科研/培训业,未婚

In [20]:
# Export the cleaned datafame to a new CSV file named 'cleaned_data.csv'
df_indexed.to_csv('cleaned_data.csv')

In [21]:
# prompt: Please merge the 'duplicate_id_cards.csv'and 'rows_with_invalid_emails.csv' into one file named 'garbage.csv'.

# Load the two CSV files into DataFrames
duplicate_df = pd.read_csv('duplicate_id_cards.csv')
invalid_emails_df = pd.read_csv('rows_with_invalid_emails.csv')

# Concatenate the two DataFrames into one
garbage_df = pd.concat([duplicate_df, invalid_emails_df], ignore_index=True)

# Export the merged DataFrame to a new CSV file named 'garbage.csv'
garbage_df.to_csv('garbage.csv', index=False)

In [22]:
garbage_df.tail()

,Name,ID card,gender,cell phone,Mail,Province,City,address,post code,Birthday,industry,marriage
18890,孙丽丽,220524198308090029,女,13944574110,1224476844@QQ. COM,吉林省,通化市,吉林省柳河县柳河镇东方红村一队,135300,1983-08-09,批发零售贸易业,已婚
18891,刘艳坤,412726197812044917,NaN,13222296517,NaN,NaN,NaN,苏州市相城区望亭镇四旺村（5）四旺弄1-4号,215000,1991-01-01,NaN,NaN
18892,宋冰杰,142301198808184810,NaN,15940527909,NaN,辽宁省,沈阳市,辽宁省沈阳市铁西区北二中路8号,110015,2014-06-17,NaN,NaN
18893,张丽萍,330623198104182225,NaN,13735561116,NaN,NaN,NaN,杭州市西湖区,310016,1991-01-01,NaN,NaN
18894,程胜男,370481198802043521,NaN,18953665647,NaN,NaN,NaN,山东省滕州市滨湖镇后盖村,277500,1991-01-01,NaN,NaN

In [23]:
df_indexed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744491 entries, 0 to 744490
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Name        744491 non-null  object
 1   ID card     744491 non-null  object
 2   gender      744491 non-null  object
 3   cell phone  744491 non-null  object
 4   Mail        744491 non-null  object
 5   Province    744491 non-null  object
 6   City        744491 non-null  object
 7   address     744491 non-null  object
 8   post code   744491 non-null  object
 9   Birthday    744491 non-null  object
 10  industry    744491 non-null  object
 11  marriage    744491 non-null  object
dtypes: object(12)
memory usage: 68.2+ MB